### ISSUE TITLE
pom file should reflect the plugin version

### ISSUE THREAD

**Issue by rsgoncalves** [NJITSABOC/oaf-protege#2]
The pom file specifies v1.0.0, while the Protege update.properties file specifies v1.1.0. What seems to happen is that this makes Protege think there's a newer plugin version, and so Protege lists the OAF plugin as if it were not installed or out-of-date.

**Comment by hl395** [comment]
Fix the version number to 1.1.0 in pom. Will release with this update. Thanks.
